# dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# deoplete.vim
[[plugins]]
repo = 'Shougo/deoplete.nvim'

# unite.vim
[[plugins]]
repo = 'Shougo/unite.vim'

# neomru.vim
[[plugins]]
repo = 'Shougo/neomru.vim'

# ctrl-P
# [[plugins]]
# repo = "ctrlpvim/ctrlp.vim"



# Color Scheme
#[[plugins]]
#repo = 'tomasr/molokai'
#hook_add = '''
#  set background=dark
#  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
#  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
#  au MyAutoCmd VimEnter * nested colorscheme molokai
#'''

